### ISSUE TITLE
細かい修正

### ISSUE THREAD

**Issue by KizahashiLuca** [KizahashiLuca/chunk_dependent_windmill_like_branch_mining_calcurator#2]
DMで話した件です。

細かいことですが、今までのツールで慣れている人のために、計算部の体裁を合わせていただきたく。

・form属性をselectからradioにしていただきたい場所
　＞計算モード ( https://github.com/KizahashiLuca/chunk_dependent_windmill_like_branch_mining_calcurator/blob/gh-pages/js/calculator_creator.js#L182-L189 )
　＞幸運エンチャント ( https://github.com/KizahashiLuca/chunk_dependent_windmill_like_branch_mining_calcurator/blob/gh-pages/js/calculator_creator.js#L251-L261 )

・form属性をtextからnumberにしていただきたい場所
　＞1チャンクあたりのダイヤ鉱石存在量 ( https://github.com/KizahashiLuca/chunk_dependent_windmill_like_branch_mining_calcurator/blob/gh-pages/js/calculator_creator.js#L198-L205 )
　＞洞窟やほか鉱石採掘中に見つかるダイヤのための補正係数 ( https://github.com/KizahashiLuca/chunk_dependent_windmill_like_branch_mining_calcurator/blob/gh-pages/js/calculator_creator.js#L206-L250 )

・周回数の入力の後ろに `周` など入れていただけると

・https://kizahashiluca.github.io/ には存在している
> Spawn Frequency: 0-40 (default 1)
1チャンクに含まれるダイヤモンドの鉱脈数 (デフォルトは１)

の記述を計算部に欲しいです
`Spawn Frequency: 0-40` はマイクラのゲーム内の表記です

細かいことばっかですが、出来たらでいいのでよろしくお願いします。

**Comment by yumetodo** [comment]
>form属性をtextからnumberにしていただきたい場所

それ少数が固定小数点になってしまうのでtextにしています

>form属性をselectからradioにしていただきたい場所

スマートフォンを考えるとradioはユーザビリティが下がるかなと思ったんですがどうでしょうか？

>周回数の入力の後ろに 周 など入れていただけると

うーん、やってみます

>Spawn Frequency: 0-40 (default 1)
1チャンクに含まれるダイヤモンドの鉱脈数 (デフォルトは１)

これの数式上の意味がいまいち理解できなかったので削除していました。

>Spawn Frequency: 0-40 はマイクラのゲーム内の表記です

というのは・・・？

**Comment by KizahashiLuca** [comment]
>> form属性をtextからnumberにしていただきたい場所
>
>それ少数が固定小数点になってしまうのでtextにしています

固定小数点ではだめでしたか？
計算は出来ませんが、アルファベットが入力できるのが気になってました

>>form属性をselectからradioにしていただきたい場所
>
>スマートフォンを考えるとradioはユーザビリティが下がるかなと思ったんですがどうでしょうか？

あっ、逆に私はradioの方がユーザビリティ上がると思いました…

>>Spawn Frequency: 0-40 (default 1)
>>1チャンクに含まれるダイヤモンドの鉱脈数 (デフォルトは１)
>
>これの数式上の意味がいまいち理解できなかったので削除していました。

1チャンクに生成される大体のダイヤモンドの鉱脈数 (そのまんま) です。
これが増えると1チャンクに生成されるダイヤモンドの鉱脈数も増えます。
未検証ですが、デフォルトでは
`(この値)×(1チャンクあたりのダイヤ鉱石存在量)=3.67`
となっていると思います。


>>Spawn Frequency: 0-40 はマイクラのゲーム内の表記です
>
>というのは・・・？

すみません。
結構前のバージョンの表記だったみたいです。
新しいワールドを作るときのカスタマイズで、鉱石設定をいじくれるのですが、ここのSpawn Triesの値とのことを言っています。

![1](https://user-images.githubusercontent.com/33852306/36153093-808f5d6e-1110-11e8-9e0e-42d67199dfe5.png)

**Comment by yumetodo** [comment]
>計算は出来ませんが、アルファベットが入力できるのが気になってました

それはまあvalidationすることにしましょう(現状でも文字列入れようとするとNaNになるはずなんですが)。精度が決め打ちになってしまうのが嫌だったので。そもそも多くのブラウザで+/-ボタンが出ていることからも小数での利用をあまり考えていないように思うので

**Comment by KizahashiLuca** [comment]
NaNはどうにか表示できないようにできないですかね？
あまりjavascriptに強くないので、条件分岐で表記を変えれるとかはわかりませんが

**Comment by yumetodo** [comment]
@KizahashiLuca 

#5 以外はやってみました。どうでしょうか？

>1チャンクに生成される大体のダイヤモンドの鉱脈数 (そのまんま) です。
これが増えると1チャンクに生成されるダイヤモンドの鉱脈数も増えます。
未検証ですが、デフォルトでは
(この値)×(1チャンクあたりのダイヤ鉱石存在量)=3.67
となっていると思います。

あれっ、ダイヤ鉱脈って1 chunkに1鉱脈がデフォルトなんですか！？(Modしかやってないせいでよくわかっていない顔)

**Comment by yumetodo** [comment]
続きは #5 へ
